### ISSUE TITLE
Некорректный JSON

### ISSUE THREAD

**Issue by slydiman** [alutov/ESP32-R4sGate-for-Redmond#46]
Вот тут https://github.com/alutov/ESP32-R4sGate-for-Redmond/issues/43 я выкладывал конфиг для Home Assistant, который приемлемо работает с RK-M171S, у которого нет подсветки.
Добавил RK-G211S с подсветкой, добавил switch для включения подсветки.
Также убрал галочку Common Command/Response Topics чтобы были разные топики для команд и состояния.
```
climate:
  - platform: mqtt
    name: Kettle2
    retain: false
    min_temp: 0
    max_temp: 100
    temp_step: 5
    precision: 1
    availability_topic: "r4s/xxx/status"
    current_temperature_topic: "r4s/xxx/rsp/temp"
    temperature_state_topic: "r4s/xxx/rsp/heat_temp"
    temperature_command_topic: "r4s/xxx/cmd/heat_temp"
    mode_command_topic: "r4s/xxx/cmd/heat_temp"
    mode_command_template: >
      {% if value == "off" %}
      0
      {% elif value == "heat" %}
      85
      {% else %}
      100
      {% endif %}
    mode_state_topic: "r4s/xxx/rsp/json"
    mode_state_template: >
      {% if value_json.state == 0 %}
      off
      {% elif value_json.target > 0 %}
      heat
      {% else %}
      auto
      {% endif %}
    modes:
      - "off"
      - "heat"
      - "auto"

sensor:
  - platform: mqtt
    name: "kettle2_temp"
    state_topic: "r4s/xxx/rsp/temp"
    unit_of_measurement: '°C'

  - platform: mqtt
    name: "kettle2_heat_temp"
    unit_of_measurement: '°C'
    state_topic: "r4s/xxx/rsp/json"
    value_template: > 
      {% if value_json.target > 0 %}
        {{ value_json.target }}
      {% elif value_json.state != 0 %}
        100
      {% else %}
        0      
      {% endif %}

  - platform: mqtt
    name: Kettle2 Подсветка
    icon: mdi:lock
    state_topic: "r4s/xxx/nightlight"
    command_topic: "r4s/xxx/cmd/nightlight"
    retain: true
```

В UI добавил подсветку:
```
          - type: custom:simple-thermostat
            entity: climate.kettle2
            header:
              name: Чайник
              icon: mdi:kettle
              toggle:
                entity: switch.kettle2_podsvetka
                name: Подсветка
            step_size: 5
            control:
              hvac:
                "off":
                  name: Выкл.
                  icon: mdi:kettle-off
                heat:
                  name: 85°C
                  icon: mdi:kettle-alert
                auto:
                  name: Кипячение
                  icon: mdi:kettle-steam
            label:
              temperature: Сейчас в чайнике
```

В интеграции climate пришлось колхозить микс из состояний и температур, потому что всё свалено в кучу.
В template нельзя указать разные топики, можно указать топик для json и использовать его содержимое.
Режим выкл/подогрев/кипячение определяется вот так:
```
    mode_state_template: >
      {% if value_json.state == 0 %}
      off
      {% elif value_json.target > 0 %}
      heat
      {% else %}
      auto
      {% endif %}
```
И это прекрасно работало пока я не захотел включить подсветку.
При nightlight=ON вдруг `json/state=2` и climate показывает режим auto, то есть кипячение.
В template я не могу проверить /rsp/state=OFF
Проблема в том что и при кипячении json/state=2 тоже! То есть state в json неправильный! Не понятно почему он меняется при включении подсветки. И уж если меняется, то пусть при кипячении там будет что-то другое. Это нужно поправить!
А по хорошему это нужно переделать полностью, например как описано в #43.
